### ISSUE TITLE
Change to less restrictive license

### ISSUE THREAD

**Issue by pascalwhoop** [tarpas/pytest-testmon#225]
Hi there!

I wanted to voice my concern with the license chosen for this project. Essentially, this project can shave off minutes from various CI projects around the world, drastically cutting back in unnecessary compute workloads. However the AGPL keeps companies from adopting this. As such, projects may be running all the tests all the time unnecessarily simply due to inconvenience of re-writing this for themselves to not be limited by the license. 

Would you consider making this slightly less restrictive, e.g. LGPL or MPL?

**Comment by pascalwhoop** [comment]
alternatively, consider making it available in a way where companies can donate some money and in exchange get to use the license, e.g. via github sponsors?

**Comment by dmitry-mukhin** [comment]
+1

**Comment by tarpas** [comment]
Hi Pascal. 

I didn't anticipate that this would be a problem. Do you think companies do any derivative work from testmon? I assume it's easy not to include pytest and pytest plugins in production environment and therefore the virality of AGPL is not a problem.
 
Developers routinely use (GPL licensed) Linux for developing commercial programs and it's not a problem to distribute the result without a source code. 
Just using AGPL software to develop a web application is also not a problem because you don't do derivative work and don't serve the AGPL software over network.

What do you think?

**Comment by dmitry-mukhin** [comment]
The problem here is that companies don't have resources to handle such risks.
So it's easier just to straight out ban anything GPL related then to fight with various auditors.
E.g.: https://opensource.google/documentation/reference/using/agpl-policy/

**Comment by tarpas** [comment]
Ok, thanks for the link. I'll change the license.

**Comment by pascalwhoop** [comment]
thx also from my side, as dmitry mentioned, my company and many others just outright ban anything that could get them into trouble. red tape..

**Comment by dmitry-mukhin** [comment]
@pascalwhoop let's keep this open for visibility?
it's easier to track.
we'll start using the package again when it's closed after license changed :)

**Comment by tarpas** [comment]
@dmitry-mukhin @pascalwhoop done and published to PYPI: https://pypi.org/project/pytest-testmon/ . Thanks for reaching out.
